site_name: Dartmouth Brain Imaging Center Handbook
site_url: https://dbic-handbook.readthedocs.io/
site_description: Documentation for users of the Dartmouth Brain Imaging Center
repo_url: https://github.com/dbic/handbook
edit_uri: edit/master/src/
copyright: See the source code and discussion pages on GitHub.
theme:
    name: material
    favicon: images/favicon.png
    logo: images/logo.png
    features:
        - navigation.footer
        - content.action.edit
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: light green
          accent: light green
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: light green
          accent: light green
          toggle:
              icon: material/weather-sunny
              name: Switch to light mode
markdown_extensions:
    - toc:
        anchorlink: true
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
    - search
docs_dir: 'src'
use_directory_urls: false
nav:
    - Home: index.md
    - Fundamentals:
      - Shell: basics/shell.md
      - SSH: computing/kerberos.md
      - Containers: basics/containers.md
      - DataLad: basics/datalad.md
      - PyBIDS: TODO.md
    - A new study:
        - Policies & procedures: https://www.dartmouth.edu/dbic/
        - JEDCap: TODO.md
        - Experimental design: TODO.md
        - Pre-registration: TODO.md
    - Stimuli/Behavioral: stimuli.md
    - MRI:
        - Overview: mri/overview.md
        - ReproIn naming convention: mri/reproin.md
        - ReproIn naming helper: https://npacore.github.io/reproin-namer/#
        - Siemens Console Walkthrough: mri/walkthrough-1.md
        - Peripherals: mri/peripherals.md
        - MR Safety: mri/safety.md
        - Data access: mri/dataaccess.md
        - Data processing:
            - QA: TODO.md
            - Preprocessing: TODO.md
            - Analysis: TODO.md
    - EEG: TODO.md
    - MRS: TODO.md
    - Computing resources:
      - Discovery HPC: computing/discovery.md
      - Jupyter on Discovery: computing/discovery-jupyter.md
      - Passwordless SSH: computing/kerberos.md
      - Troubleshooting: computing/troubleshooting.md
    - Publishing:
        - Datasets: TODO.md
        - Data papers: publishing/data-paper.md
        - Study papers: TODO.md
    - Appendix:
        - Contributors: 99-appendices/01-contributors.md
        - Licenses: 99-appendices/02-licenses.md
    - Additional resources: additional_resources.md
    - Changelog: CHANGES.md
    - Contributing: CONTRIBUTING.md
    - Code of Conduct: CODE_OF_CONDUCT.md
